#!/bin/bash
# reference: https://github.com/google/macops-keychainminder/blob/master/Package/postinstall

# Load Daemon
[[ $3 != "/" ]] && exit 0
/bin/launchctl load /Library/LaunchDaemons/com.clburlison.pinpoint.plist

exit 0
